version: "3.8"

services:
  autobuyer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-gift-autobuyer
    env_file:
      - temp.env
    volumes:
      - app_data:/app
    restart: unless-stopped
    command: python main.py
    stdin_open: true
    tty: true

volumes:
  app_data:
